import Head from 'next/head'
import Image from 'next/image'
import { PostWidgets, PostCard, Categories } from '../components'

const posts = [
    { title: "React App", excerpt: 'Learn reactJS M<CBEWCVcsrkv ' },
    { title: 'Next App', excerpt: "learn NextJS jsabcjka" }
]



export default function Home() {
    return (
        <div className='container mx-auto px-10 mb-8'>
            <Head>
                <title>CritiQue</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/Critique-2.svg" />
            </Head>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
                <div className="lg:col-span-8 col-span-1">
                    {posts.map((post) => <PostCard post={post} key={post.title} />)}
                </div>
                <div className="lg:col-span-4 col-span-1">
                    <div className="lg:sticky relative top-8">
                        <PostWidgets />
                        <Categories />
                    </div>
                </div>
            </div>



        </div>
    )
}
